proto_outdir = "./proto"

[[dependencies]]
  target = "github.com/stormcat24/protodep/protobuf"
  branch = "master"
  
[[dependencies]]
  target = "github.com/googleapis/api-common-protos"
  branch = "master"
  path = "proto"
  
[[dependencies]]
  target = "github.com/gogo/protobuf"
  revision = "v1.3.2"
  path = "proto"
  
[[dependencies]]
  target = "github.com/cosmos/cosmos-sdk"
  revision = "v0.42.11"
  path = "proto"
  
[[dependencies]]
  target = "github.com/tendermint/tendermint"
  revision = "v0.35.0"
  path = "proto"
  
[[dependencies]]
  target = "github.com/Pylons-tech/pylons_protos"
  path = "proto"
  branch = "develop"