proto_outdir = "./prototmp"

[[dependencies]]
  target = "github.com/stormcat24/protodep/protobuf"
  branch = "master"
  
[[dependencies]]
  target = "github.com/googleapis/api-common-protos"
  branch = "master"
  
[[dependencies]]
  target = "github.com/regen-network/protobuf"
  revision = "v1.3.3-alpha.regen.1"
  
[[dependencies]]
  target = "github.com/cosmos/cosmos-proto/proto"
  branch = "main"
  
[[dependencies]]
  target = "github.com/cosmos/cosmos-sdk/proto"
  revision = "v0.42.11"
  
[[dependencies]]
  target = "github.com/tendermint/spec/proto"
  revision = "v0.7"
