name: Generate schema

on: push

jobs:
  my-job:
    name: Generate schema
    runs-on: ubuntu-latest
    steps:
      - name: Install protoc
        uses: arduino/setup-protoc@v1
        
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.16
        
      - name: Install protoc-gen-jsonschema
        run: |
          GO111MODULE=on \
          go get github.com/chrusty/protoc-gen-jsonschema/cmd/protoc-gen-jsonschema
          go install github.com/chrusty/protoc-gen-jsonschema/cmd/protoc-gen-jsonschema@latest
          
      - name: Install protodep
        run: go get github.com/stormcat24/protodep@latest
          
      - uses: actions/checkout@v1
          
      - name: Make staging folder
        run: mkdir prototmp
          
      - name: Grab proto dependencies
        run: protodep up -u -f
        
      - name: Emit schema
        run: |
          mkdir schema/pylons/
          cp -a proto/* prototmp
          protoc --proto_path=prototmp/ --jsonschema_out=schema/pylons/ prototmp/pylons/*
          
      - name: Add & Commit
        # You may pin to the exact commit or the version.
        # uses: EndBug/add-and-commit@8c12ff729a98cfbcd3fe38b49f55eceb98a5ec02
        uses: EndBug/add-and-commit@v7.5.0
        with:
          # Arguments for the git add command
          add: schema/pylons/*
          # The name of the user that will be displayed as the author of the commit
          author_name: SchemaBot
          # The email of the user that will be displayed as the author of the commit
          author_email: i@pylons.tech
          # Arguments for the git pull command. Use NO-PULL to avoid the action pulling at all.
          pull: NO-PULL

