name: Generate schema

on: push

jobs:
  my-job:
    name: Generate schema
    runs-on: ubuntu-latest
    steps:
      - name: Install protoc
        uses: arduino/setup-protoc@v1
        
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.16
        
      - name: Install protoc-gen-jsonschema
        run: |
          GO111MODULE=on \
          go get github.com/chrusty/protoc-gen-jsonschema/cmd/protoc-gen-jsonschema
          go install github.com/chrusty/protoc-gen-jsonschema/cmd/protoc-gen-jsonschema@latest
          
      - uses: actions/checkout@v1
          
      - name: Emit schema
        run: |
          protoc  --jsonschema_out=schema --proto_path=proto/pylons/*
          
      - name: Push commit
        run: | 
          git status
          git add .
          git commit -m "Emit JsonSchema for protos"
          git fetch origin actions
          git push origin HEAD:actions
